[project]
name = "polyglot-sql-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "botan", email = "aginbotan@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "polyglot-sql>=0.3.5",
    "typer>=0.25.1",
]

[project.scripts]
polyglot-sql-cli = "polyglot_sql_cli:main"

[build-system]
requires = ["uv_build>=0.11.8,<0.12.0"]
build-backend = "uv_build"
