[project]
name = "transpile"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "botan", email = "aginbotan@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "polyglot-sql>=0.3.5",
    "typer>=0.25.1",
]

[project.scripts]
transpile = "transpile.cli:main"

[build-system]
requires = ["uv_build>=0.11.8,<0.12.0"]
build-backend = "uv_build"

[tool.ruff]
line-length = 100
target-version = "py313"

[tool.ty]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "ruff>=0.15.12",
    "ty>=0.0.34",
]
